### PR TITLE
Updated fr.ts

### PR DESCRIPTION
**Pull request by deatheguard**
I have looked through and fixed some typos of the French translation. 

I just have to note for the line 11, day, when we count in French, most numbers will finish in "me": seventy fifth is soixante-quinzième etc. The only difference is the first day, which would end in "r" (premier jour). Maybe it would be possible to add a separate line for the first day or this could simply be disregarded.

### CODE REVIEW

**Comment by IraSoro** [comment]
Hello, @deatheguard! Thank you for your interest in the project!

Thank you very much for finding the mistakes and correcting them! We also will correct what you wrote in the comment.

Could you also answer a few more questions related to the translation?
I think there is a misspelling of the word "Days". 
{222C6969-8AA4-459C-926F-013A2DD1443D}
Could you please look and check. 

How would you write the phrases in French:
"Today is day 21 of the cycle"
"The length of the cycle is 28 days"
"Period in 10 days"

**Review by IraSoro — DISMISSED** [review]

**Comment by deatheguard** [comment]
Hello @IraSoro!

I am glad to have helped!

Considering your questions: 1) on the screenshot, it would be correct to use the plural everywhere - "21 jours" (both at the top and in the list), "13 jours";
2) I would say these phrases like that:
'Aujourd'hui on est au vingt-et-unième jour du cycle' (or 'Aujourd'hui c'est le vingt-et-unième jour du cycle' works too)
'La durée du cycle est de vingt-huit jours' ('La durée du cycle consiste de vingt-huit jours')
'Les règles [commencent] dans dix jours'

**Comment by IraSoro** [comment]
Hello, @deatheguard! I fixed what we discussed above. I also fixed `translation.ts` file because there was a bug when switching the French language.

Please check it and write if I'm wrong somewhere.

**Review by imblowfish — APPROVED** [review]

**Review by IraSoro — DISMISSED** [review]

**Comment by IraSoro** [comment]
@deatheguard, I fixed what we discussed above. Please check it and write if I'm wrong somewhere.

**Review by imblowfish — APPROVED** [review]

**Comment by deatheguard** [comment]
> @deatheguard, I fixed what we discussed above. Please check it and write if I'm wrong somewhere.

Hi, @IraSoro 
Could you please send me a link to the fixed version? Thank you (I'm not home rn)

**Comment by imblowfish** [comment]
> > @deatheguard, I fixed what we discussed above. Please check it and write if I'm wrong somewhere.
> 
> Hi, @IraSoro Could you please send me a link to the fixed version? Thank you (I'm not home rn)

https://github.com/IraSoro/peri/pull/302/commits/f96d7100bcdf5f2ac2ab4a47a9c2e2682a01af19

**Comment by deatheguard** [comment]
@imblowfish thank you for the link
@IraSoro I believe it should be (0)[Jour] (I was not sure, so I googled, and it seems that in the context of 0 days the "day" should be singular in French.
Otherwise, all seems good!

**Review by IraSoro — APPROVED** [review]

**Review by imblowfish — APPROVED** [review]

**Comment by IraSoro** [comment]
@deatheguard, congratulations on your first contribution to the `Peri` project! 

Thank you for your interest in the project and help with correcting the translation! We appreciate it!

And Happy Hacktoberfest!

**Pull request merged**
