### PR TITLE
Hacktoberfest : Added Hinglish 

### PR DESCRIPTION
**Pull request by IntegerAlex**
Made fixes for auto-checks

### CODE REVIEW

**Review by imblowfish — DISMISSED** [review]

**Comment by IraSoro** [comment]
Hello, @IntegerAlex and @akshatkot. Everything looks good!

I'd like to ask one question. Will this display be correct?
{E7B7397E-8F90-4785-94F5-B64DF557236B}

I asked chatGPT about the translation. It wrote me the following answer:
{BF9A4241-C257-482F-A31A-21F9FB079A64}

Does the display not contradict the rules of the language?

**Comment by IraSoro** [comment]
@IntegerAlex and @akshatkot, I have made a few changes to the PR:

1. Added language to `fallbackLng` as described in the [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md) file in section 7
2. I renamed the language from `hi` to `hg` in the `hg.ts` file because the name `hg` is used everywhere
3. I also changed the locale for dates from `hi` to `enUS` because I thought it would be better in this case if the dates were displayed in English instead of Hindi.

Please write to me if you think I'm wrong.

**Comment by IntegerAlex** [comment]
> @IntegerAlex and @akshatkot, I have made a few changes to the PR:
> Please write to me if you think I'm wrong.

You are right

**Comment by IntegerAlex** [comment]
> Hello, @IntegerAlex and @akshatkot. Everything looks good!
> 
> I'd like to ask one question. Will this display be correct? {E7B7397E-8F90-4785-94F5-B64DF557236B}
> 
> I asked chatGPT about the translation. It wrote me the following answer: {BF9A4241-C257-482F-A31A-21F9FB079A64}
> 
> Does the display not contradict the rules of the language?
No, its same. I verified with a med student.

**Comment by IntegerAlex** [comment]
If there are any changes i will maintain the translation, Don't worry

**Comment by IraSoro** [comment]
> If there are any changes i will maintain the translation, Don't worry

Everything is fine, I just fixed merge conflicts. Thank you

**Review by IraSoro — APPROVED** [review]

**Review by imblowfish — APPROVED** [review]

**Comment by IraSoro** [comment]
@IntegerAlex and @akshatkot Congratulations on your first contribution to `peri`, thank you!

**Pull request merged**
