### PR TITLE
Fixed case if user removes all cycles

### LINKED ISSUE #166: You can't delete all cycles in the calendar
If you remove all marked days from the calendar, then click the `Save button`, new empty array of cycles will not be saved.

The problem is with this check
```
if (datetimeRef.current?.value) {
```

### PR DESCRIPTION
**Pull request by imblowfish**
Fixed #166

In this PR I added possibility to save empty array of cycles. Also I removed `isMarkedFutureDays` because now we using ion-datetime built-in limitation instead of custom checks

New test has been added https://github.com/IraSoro/peri/issues/192

### CODE REVIEW

**Comment by imblowfish** [comment]
@IraSoro could you give me rights for `peri-tests` project or add test https://github.com/IraSoro/peri/issues/192 by yourself?

**Review by IraSoro — COMMENTED** [review]
Read more about this https://github.com/IraSoro/peri/pull/178 and this https://github.com/IraSoro/peri/issues/155 . 

Firstly, the previous solution did not fix the bug. Below I will describe the steps.
Secondly, you need to leave checking future cycles and editing the current period. The user must be able to edit the current cycle. I missed this in previous PR.

**Comment by imblowfish** [comment]
@IraSoro based on steps that you described, looke like you confused this issue with https://github.com/IraSoro/peri/issues/171
In this issue we just fixing problem when user trying to remove all cycles, but can't do that, because we have `datetimeRef` value check. I fixed this problem and now you can remove all cycles from the storage.

The problem what you described above is fixed in this PR https://github.com/IraSoro/peri/pull/196. I checked by myself and everything works fine. And also you can see, that out of 4 commits from https://github.com/IraSoro/peri/pull/196, 3 are completely duplicates commits from the current PR.

**Comment by imblowfish** [comment]
I closed this PR because https://github.com/IraSoro/peri/pull/196 has the same changs

**Pull request closed without merging**
