### PR TITLE
added german translation 

### PR DESCRIPTION
**Pull request by singhvibhanshu**
I created `de.ts`, which has the German translation without changing the meaning of any words or sentences. I also updated `translation.ts` and `datetime.ts` for the necessary changes mentioned in `contributing.md`.

### CODE REVIEW

**Review by IraSoro — CHANGES_REQUESTED** [review]
Hello, @singhvibhanshu! Thank you for your interest in our project!

Looks like you PR didn't pass formatter checks.  Could you please run
```
npm run fmt
```
and push the changes.

I also have some translation related questions that I'd like to discuss. Can you please tell me if you are a native speaker?

**Comment by singhvibhanshu** [comment]
Hello @IraSoro. Sure, I could run the format checker test. No, I am not a native German speaker.

**Comment by IraSoro** [comment]
> Hello @IraSoro. Sure, I could run the format checker test. No, I am not a native German speaker.

@singhvibhanshu, we have a few questions related to the specifics of the German language. Do you have any knowledge of German that could help us address them?

**Comment by singhvibhanshu** [comment]
Hey @IraSoro  I have a basic understanding of German, as learning the language is a hobby of mine. Initially, I started adding Hindi translations to your app, but halfway through, I realized that Hindi translations were already available. I didn’t want my work to go to waste, so I switched to adding German translations. I already know some common words in German like 'today', 'tomorrow', etc., and for the words or sentences I wasn’t sure of, I either Googled them or used AI to help.

**Comment by IraSoro** [comment]
@singhvibhanshu, thank you for your time! Unfortunately, the translation into German has just been completed by someone else. But we'd like to see more of your work on other tasks. For example, you said that you started translating to Hindi, but that translation has already been completed. You can check that translation and fix any mistakes if you find them. We appreciate your help!

**Comment by singhvibhanshu** [comment]
Sure, I would love to do that. Thanks @IraSoro

**Pull request closed without merging**
