### PR TITLE
Add French Translation for Peri Application

### PR DESCRIPTION
**Pull request by HackesticMedusa**
### Description:
This pull request adds a complete French translation for the Peri app. The translation covers all user interface elements, including the Home Tab, Details Tab, Mark Modal, Welcome Modal, Info Modal, and various phases of the menstrual cycle. 

#### Changes Made:
- Added `fr.ts` file with French translations.
- Updated the `supportedLanguages` array to include French.
- Ensured consistency with existing translations by following the structure and format of the `ru.ts` and `es.ts` files.

#### How to Test:
1. Switch the app language to French in the Preferences menu.
2. Navigate through the app to verify that all text elements are correctly translated.
3. Check for any missing or incorrect translations and report them.

#### Additional Notes:
- This translation was done as part of the [Hacktoberfest](https://hacktoberfest.com/) contribution.
- Please review the translations for accuracy and provide feedback if any changes are needed.

Thank you for considering this contribution!

### CODE REVIEW

**Review by imblowfish — CHANGES_REQUESTED** [review]
Hello, could you please run

```shell
npm run fmt
```

on your PR, commit changes and push them?

Looks like you project didn't pass formatter checks

**Comment by HackesticMedusa** [comment]
> Hello, could you please run
> 
> ```shell
> npm run fmt
> ```
> 
> on your PR, commit changes and push them?
> 
> Looks like you project didn't pass formatter checks

Okay sir

**Review by imblowfish — APPROVED** [review]

**Review by IraSoro — APPROVED** [review]

**Comment by IraSoro** [comment]
@HackesticMedusa I set `hacktoberfest-accepted` and merged your PR
Thank you for your contribution!
Please write here if anything wrong on Hacktoberfest side, I'll revert changes and merge them again

**Comment by HackesticMedusa** [comment]
@IraSoro & @imblowfish can I add some more translations? I would like to do some more contributions.

**Comment by HackesticMedusa** [comment]
> > @IraSoro & @imblowfish can I add some more translations? I would like to do some more contributions.
> 
> If you want, of course you can, thank you

If you have a moment, could you please take a look at Pull Request #292 that I contributed to? Thank you so much!

**Pull request merged**
