### PR TITLE
Added the last period force remove if user unmarked the first day of the last period

### LINKED ISSUE #166: You can't delete all cycles in the calendar
If you remove all marked days from the calendar, then click the `Save button`, new empty array of cycles will not be saved.

The problem is with this check
```
if (datetimeRef.current?.value) {
```

### LINKED ISSUE #171: Bug when marking periods
Steps:

1. Let your period be today

Image

2. Click the 'Mark button'

Image

3. Edit marked days like this

Image

4. And save it

Image

### PR DESCRIPTION
**Pull request by imblowfish**
Closed #166
Closed #171

In this PR I added possibility to save empty array of cycles. Also I removed isMarkedFutureDays because now we using ion-datetime built-in limitation instead of custom checks
Also I added the new test https://github.com/IraSoro/peri/issues/195

### CODE REVIEW

**Comment by imblowfish** [comment]
@IraSoro please give me rights to modify `peri-tests` projects. I cannot add this test https://github.com/IraSoro/peri/issues/195 in this project

**Comment by imblowfish** [comment]
@IraSoro I agree with the first bug. It was because I believed in the variable name `lastPeriodDays` and didn't check twice what it stores. It turned out that this variables stores all dates instead of the last period days. To fix that I renamed current `getLastPeriodDays` function to `getPeriodDays` and added the new `lastPeriodDays` function which returns what is promised in the name

About the second bug. I cannot reproduce what you described. As example, I generated 2 cycles
image
image
And we have forecast period here
image

Let's click on `Edit` and this is what we get
image
As expected, edit calendar will open the last cycle to edit

Let's click on `Mark` and we'll get
image

Let's click on `Edit` again
image
As you can see edit calendar shows December as expected

**Review by IraSoro — COMMENTED** [review]
Everything is fine. Just add the ability to edit future days.

**Comment by IraSoro** [comment]
@imblowfish please check the last commit

**Review by IraSoro — APPROVED** [review]

**Comment by imblowfish** [comment]
> @imblowfish please check the last commit

All fine

**Pull request merged**
