### PR TITLE
Add german translation

### PR DESCRIPTION
**Pull request by Abhinav-Bansal751**
Add German translations for the app

Purpose: This PR adds support for German  addressing issue #279 

Changes:

    Added de.ts for German translations.
    Updated translations.ts to include the new language.
    Added German supportedLanguages, resources, and locales.

Testing:

    Ran npm run lint and npm run fmt to check formatting and linting.

### CODE REVIEW

**Comment by Abhinav-Bansal751** [comment]
This PR is part of my Hacktoberfest contributions!

**Comment by Abhinav-Bansal751** [comment]
@imblowfish @IraSoro pls review it

**Comment by imblowfish** [comment]
Hello @Abhinav-Bansal751, thank you for your contribution!
I have a question, are you german native speaker? Me and @IraSoro have some questions related to German trbalsation which we need to discuss

**Comment by Abhinav-Bansal751** [comment]
No sir, I am not native German speaker

**Comment by imblowfish** [comment]
It's not a problem. In this case we just need more time to check you PR

**Pull request closed without merging**
