### PR TITLE
Hacktoberfest: added support for tagalog translation

### PR DESCRIPTION
**Pull request by jcgaming-official**
Added my local language which is tagalog.
#279

### CODE REVIEW

**Comment by IraSoro** [comment]
Hello, @jcgaming-official! Thanks for contributing to the project!

It looks like your PR didn't pass the auto checks. This is our first time participating in Hacktoberfest. We have rewritten the `CONTRIBUTING.md` file with more precise instructions.

If it's not difficult, please fix what is described in sections 8, 9, 10, 11 in [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md). 

Or I can do it myself. Then please write your locale from those available in the [date-fns](https://date-fns.org/).

**Comment by jcgaming-official** [comment]
> Hello, @jcgaming-official! Thanks for contributing to the project!
> 
> It looks like your PR didn't pass the auto checks. This is our first time participating in Hacktoberfest. We have rewritten the `CONTRIBUTING.md` file with more precise instructions.
> 
> If it's not difficult, please fix what is described in sections 8, 9, 10, 11 in [CONTRIBUTING.md](https://github.com/IraSoro/peri/blob/master/CONTRIBUTING.md). 
> 
> Or I can do it myself. Then please write your locale from those available in the [date-fns](https://date-fns.org/).

My bad. I'll do it later. Thanks

**Review by imblowfish — APPROVED** [review]

**Comment by imblowfish** [comment]
> what im doing wrong here?
> image
> 
Looks like `tl` locale is not supported by date-fns library https://github.com/date-fns/date-fns/tree/main/src%2Flocale

**Comment by jcgaming-official** [comment]
> > what im doing wrong here?
> > image
> 
> Looks like `tl` locale is not supported by date-fns library https://github.com/date-fns/date-fns/tree/main/src%2Flocale

yes they removed it since 2.29.0 :( https://github.com/date-fns/date-fns/pull/3393#issuecomment-1588466790

**Comment by imblowfish** [comment]
Is there some backup locale you use if you don't have Tagalog?

**Comment by IraSoro** [comment]
Hello, @jcgaming-official! I read that one of the official languages ​​in the Philippines is English. Since there is no suitable locale in the `date-fns` library, I decided to leave the `enUS` locale for now. And I created a [task](https://github.com/IraSoro/peri/issues/309) for the future, when the locale is added to the library.
Please write if I'm wrong.

**Review by IraSoro — DISMISSED** [review]

**Comment by IraSoro** [comment]
> Hello, @jcgaming-official! I read that one of the official languages ​​in the Philippines is English. Since there is no suitable locale in the `date-fns` library, I decided to leave the `enUS` locale for now. And I created a [task](https://github.com/IraSoro/peri/issues/309) for the future, when the locale is added to the library. Please write if I'm wrong.

Hello, @jcgaming-official!
I’ve made changes to your PR and want to make sure everything is correct. Can you please check and let me know if it’s OK? If everything is good, I'm ready to merge the PR.
Thanks!

**Comment by jcgaming-official** [comment]
> > Hello, @jcgaming-official! I read that one of the official languages ​​in the Philippines is English. Since there is no suitable locale in the `date-fns` library, I decided to leave the `enUS` locale for now. And I created a [task](https://github.com/IraSoro/peri/issues/309) for the future, when the locale is added to the library. Please write if I'm wrong.
> 
> Hello, @jcgaming-official!
> I’ve made changes to your PR and want to make sure everything is correct. Can you please check and let me know if it’s OK? If everything is good, I'm ready to merge the PR.
> Thanks!

Hello @IraSoro , I apologize for my late response. Your changes are everything looks good. I thought I was the only one facing the same issue. I appreciate your effort. Thank you

**Review by imblowfish — APPROVED** [review]

**Review by IraSoro — APPROVED** [review]

**Comment by IraSoro** [comment]
@jcgaming-official, congratulations on your first contribution to the `Peri` project, thank you!

**Pull request merged**
